# Generated by Django 2.1.5 on 2019-02-07 17:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sharable', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('open', 'open'), ('shared', 'shared'), ('confirmed', 'confirmed'), ('completed', 'completed')], default='open', max_length=10)),
                ('destination', models.CharField(max_length=200)),
                ('passenger_num', models.IntegerField(default=1)),
                ('total_passenger', models.IntegerField(default=1)),
                ('vehicle_type', models.CharField(choices=[('sedan', 'sedan'), ('suv', 'suv'), ('coupe', 'coupe'), ('van', 'van'), ('hyper', 'hyper')], default='sedan', max_length=6)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Create Date')),
                ('arrival_time', models.DateTimeField(blank=True, default=datetime.datetime(2019, 2, 7, 17, 13, 10, 424560, tzinfo=utc), null=True)),
                ('special_vehicle_info', models.TextField(blank=True, null=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_owner_request_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SharerRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=200)),
                ('earliest_time', models.DateTimeField(blank=True, default=datetime.datetime(2019, 2, 7, 17, 13, 10, 425076, tzinfo=utc), null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Create Date')),
                ('latest_time', models.DateTimeField(blank=True, default=datetime.datetime(2019, 2, 7, 17, 13, 10, 425108, tzinfo=utc), null=True)),
                ('passenger_num', models.IntegerField(default=1)),
                ('vehicle_type', models.CharField(choices=[('sedan', 'sedan'), ('suv', 'suv'), ('coupe', 'coupe'), ('van', 'van'), ('hyper', 'hyper')], max_length=6)),
                ('owner_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ride.OwnerRequest')),
                ('sharer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=10)),
                ('volume', models.IntegerField()),
                ('vehicle_type', models.CharField(choices=[('sedan', 'sedan'), ('suv', 'suv'), ('coupe', 'coupe'), ('van', 'van'), ('hyper', 'hyper')], max_length=6)),
                ('special_vehicle_info', models.TextField(blank=True, null=True)),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
