# Generated by Django 2.1.5 on 2019-02-02 02:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ride.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(ride.models.OrderStatus('open'), 'open'), (ride.models.OrderStatus('confirmed'), 'confirmed'), (ride.models.OrderStatus('completed'), 'completed')], max_length=10)),
                ('destination', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SharerRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ride.OwnerRequest')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('plate_number', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('type', models.CharField(choices=[(ride.models.VehicleType('sedan'), 'sedan'), (ride.models.VehicleType('suv'), 'suv'), (ride.models.VehicleType('coupe'), 'coupe'), (ride.models.VehicleType('van'), 'van'), (ride.models.VehicleType('hyper'), 'hyper')], max_length=6)),
            ],
        ),
        migrations.AddField(
            model_name='ownerrequest',
            name='owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
