# Generated by Django 2.1.5 on 2019-02-02 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ride', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerrequest',
            name='arrival_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ownerrequest',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Create Date'),
        ),
        migrations.AddField(
            model_name='ownerrequest',
            name='passenger_num',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ownerrequest',
            name='total_passenger',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='sharerrequest',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Create Date'),
        ),
        migrations.AddField(
            model_name='sharerrequest',
            name='earliest_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sharerrequest',
            name='latest_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sharerrequest',
            name='passenger_num',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='sharerrequest',
            name='sharer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
