# Generated by Django 2.1.5 on 2019-02-06 16:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownerrequest',
            name='arrival_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 2, 6, 16, 39, 18, 620226, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='sharerrequest',
            name='earliest_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 2, 6, 16, 39, 18, 620802, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='sharerrequest',
            name='latest_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 2, 6, 16, 39, 18, 620835, tzinfo=utc), null=True),
        ),
    ]
