# Generated by Django 2.1.5 on 2019-02-04 18:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0002_auto_20190204_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownerrequest',
            name='arrival_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 2, 4, 18, 31, 34, 327610, tzinfo=utc), null=True),
        ),
    ]
