# Generated by Django 2.1.5 on 2019-02-03 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0002_auto_20190202_1442'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ownerrequest',
            old_name='owner_id',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='sharerrequest',
            old_name='owner_request_id',
            new_name='owner_request',
        ),
        migrations.RenameField(
            model_name='sharerrequest',
            old_name='sharer_id',
            new_name='sharer',
        ),
    ]
