# Generated by Django 2.1.5 on 2019-02-07 17:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0002_auto_20190207_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownerrequest',
            name='arrival_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 2, 7, 17, 25, 15, 224218, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='sharerrequest',
            name='earliest_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 2, 7, 17, 25, 15, 224867, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='sharerrequest',
            name='latest_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 2, 7, 17, 25, 15, 224908, tzinfo=utc), null=True),
        ),
    ]
