# Generated by Django 2.1.5 on 2019-02-05 06:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0009_auto_20190204_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharerrequest',
            name='destination',
            field=models.CharField(default='sss', max_length=200),
        ),
        migrations.AddField(
            model_name='sharerrequest',
            name='vehicle_type',
            field=models.CharField(choices=[('sedan', 'sedan'), ('suv', 'suv'), ('coupe', 'coupe'), ('van', 'van'), ('hyper', 'hyper')], default='sedan', max_length=6),
        ),
        migrations.AlterField(
            model_name='ownerrequest',
            name='arrival_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 2, 5, 6, 33, 12, 235162, tzinfo=utc), null=True),
        ),
    ]
